#ifndef PIN_CFG_H
#define PIN_CFG_H

#include <avr/io.h>

#define DISPLAY_CONTROLLER_CLK	(1 << PB0)
#define DISPLAY_CONTROLLER_DIO	(1 << PB1)
#define DISPLAY_CONTROLLER_PORT	(DDRB)
#define DISPLAY_CONTROLLER_OUT	(PORTB)
#define DISPLAY_CONTROLLER_IN	(PINB)


#endif